name: Test and deploy auth-service
on: [workflow_dispatch]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: go test ./...
    
  build:
    runs-on: ubuntu-latest
    outputs:
      exe-file-name: $${{ steps.publish.outputs }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: env GOOS=linux CGO_ENABLED=0 go build -o authService ./cmd/api
      - name: Publish exe name
        id: publish
        run: echo 'exe-file-name=authService' >> $GITHUB_OUTPUT ';'
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output file
        run: echo "${{ needs.build.output.exe-file-name}}"
      - name: Deploy
        run: echo "Deploying..."

