name: Test and deploy auth-service
on: [workflow_dispatch]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: go test ./...
    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: env GOOS=linux CGO_ENABLED=0 go build ./...