name: Push to DockerHub on tag
on:
  push:
    tags:
      - 'v*'
jobs:
  push_to_registry_x:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Current tag
        run: echo ${{ github.ref_name }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth-service.dockerfile
          push: true
          tags: clydotron/auth-service:${{ github.ref_name }}

