# builds and pushes a docker image to docker hub when a tag is created.
name: Push to DockerHub
on:
  push:
    tags:
      - 'v*'
jobs:
  push_to_docker_hub:
    name: Build and Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth-service.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.ref_name }}

